function [A,B] = DAE_matrices(in1,in2)
%DAE_matrices
%    [A,B] = DAE_matrices(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-May-2025 16:19:19

I1 = in2(7,:);
I2 = in2(8,:);
I3 = in2(9,:);
d1 = in2(4,:);
d2 = in2(5,:);
d3 = in2(6,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(10,:);
m2 = in2(11,:);
m3 = in2(12,:);
theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
thetadot1 = in1(4,:);
thetadot2 = in1(5,:);
thetadot3 = in1(6,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = cos(theta3);
t5 = sin(theta1);
t6 = sin(theta2);
t7 = sin(theta3);
t8 = d2.^2;
t9 = d3.^2;
t10 = l1.^2;
t11 = l2.^2;
t12 = thetadot1.^2;
t13 = thetadot2.^2;
t14 = thetadot3.^2;
t15 = -I2;
t16 = -I3;
t17 = -theta2;
t18 = -theta3;
t19 = m2.*t10;
t20 = m3.*t10;
t21 = m3.*t11;
t22 = m2.*t8.*2.0;
t23 = m3.*t9.*2.0;
t24 = t17+theta1;
t25 = t18+theta1;
t26 = t18+theta2;
t30 = d2.*m2.*t6.*1.0e+1;
t31 = d3.*m3.*t7.*1.0e+1;
t35 = l2.*m3.*t6.*1.0e+1;
t36 = l1.*t5.*t12;
t27 = cos(t24);
t28 = cos(t25);
t29 = cos(t26);
t32 = sin(t24);
t33 = sin(t25);
t34 = sin(t26);
t37 = -t22;
t38 = -t23;
t39 = -t19;
t40 = -t20;
t41 = -t21;
t42 = d3.*l2.*m3.*t29;
t43 = l1.*l2.*m3.*t27;
t48 = d3.*l2.*m3.*t13.*t34;
t49 = d3.*l2.*m3.*t14.*t34;
t44 = t42.*3.0;
t45 = -t42;
t47 = -t43;
t50 = -t48;
t46 = -t44;
A = reshape([d1.*m1.*t5+l1.*m2.*t5+l1.*m3.*t5,-d1.*m1.*t2-l1.*m2.*t2-l1.*m3.*t2,-I1+t39+t40+t47-d1.^2.*m1.*2.0-d2.*l1.*m2.*t27-d3.*l1.*m3.*t28,0.0,0.0,d2.*m2.*t6+l2.*m3.*t6,-d2.*m2.*t3-l2.*m3.*t3,t15+t37+t39+t41+t45+t47-d2.*l1.*m2.*t27.*3.0,t15+t37+t41+t45,0.0,d3.*m3.*t7,-d3.*m3.*t4,t16+t38+t40+t41-t43.*2.0+t46-d3.*l1.*m3.*t28.*3.0,t16+t38+t41+t46,t16+t38,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[5,5]);
if nargout > 1
    B = [m1.*-1.0e+1-m2.*1.0e+1-m3.*1.0e+1-d1.*m1.*t2.*t12-d2.*m2.*t3.*t13-d3.*m3.*t4.*t14-l1.*m2.*t2.*t12-l1.*m3.*t2.*t12-l2.*m3.*t3.*t13;-m2.*(t36+d2.*t6.*t13)-m3.*(t36+d3.*t7.*t14+l2.*t6.*t13)-d1.*m1.*t5.*t12;t30+t31+t35+t49+t50+d1.*m1.*t5.*1.0e+1+l1.*m2.*t5.*1.0e+1+l1.*m3.*t5.*1.0e+1-d2.*l1.*m2.*t12.*t32+d2.*l1.*m2.*t13.*t32-d3.*l1.*m3.*t12.*t33+d3.*l1.*m3.*t14.*t33-l1.*l2.*m3.*t12.*t32+l1.*l2.*m3.*t13.*t32;t30+t31+t35+t49+t50;t31];
end
end
