function [A,B] = Lagrange_matrices(in1,in2)
%Lagrange_matrices
%    [A,B] = Lagrange_matrices(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-May-2025 11:57:25

I1 = in2(7,:);
I2 = in2(8,:);
I3 = in2(9,:);
d1 = in2(4,:);
d2 = in2(5,:);
d3 = in2(6,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(10,:);
m2 = in2(11,:);
m3 = in2(12,:);
theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
thetadot1 = in1(4,:);
thetadot2 = in1(5,:);
thetadot3 = in1(6,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = l1.^2;
t5 = thetadot1.^2;
t6 = thetadot2.^2;
t7 = thetadot3.^2;
t8 = -theta2;
t9 = -theta3;
t10 = t8+theta1;
t11 = t9+theta1;
t12 = t9+theta2;
t13 = cos(t10);
t14 = cos(t11);
t15 = cos(t12);
t16 = sin(t10);
t17 = sin(t11);
t18 = sin(t12);
t19 = d2.*l1.*m2.*t13;
t20 = d3.*l1.*m3.*t14;
t21 = d3.*l2.*m3.*t15;
t22 = l1.*l2.*m3.*t13;
t23 = t19+t22;
A = reshape([I1+m2.*t4+m3.*t4+d1.^2.*m1,t23,t20,t23,I2+d2.^2.*m2+l2.^2.*m3,t21,t20,t21,I3+d3.^2.*m3],[3,3]);
if nargout > 1
    B = [d1.*m1.*t2.*-1.0e+1-l1.*m2.*t2.*1.0e+1-l1.*m3.*t2.*1.0e+1-d2.*l1.*m2.*t6.*t16-d3.*l1.*m3.*t7.*t17-l1.*l2.*m3.*t6.*t16;d2.*m2.*t3.*-1.0e+1-l2.*m3.*t3.*1.0e+1+d2.*l1.*m2.*t5.*t16-d3.*l2.*m3.*t7.*t18+l1.*l2.*m3.*t5.*t16;d3.*m3.*sin(theta3).*-1.0e+1+d3.*l1.*m3.*t5.*t17+d3.*l2.*m3.*t6.*t18];
end
end
