function [A,B] = NE_matrices(in1,in2)
%NE_matrices
%    [A,B] = NE_matrices(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    17-May-2025 16:28:42

I1 = in2(7,:);
I2 = in2(8,:);
I3 = in2(9,:);
d1 = in2(4,:);
d2 = in2(5,:);
d3 = in2(6,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(10,:);
m2 = in2(11,:);
m3 = in2(12,:);
theta1 = in1(1,:);
theta2 = in1(2,:);
theta3 = in1(3,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
t6 = sin(theta3);
t7 = d3.^2;
t9 = -I2;
t10 = -I3;
t8 = l1.*t2;
t11 = d2.*t5;
t12 = d3.*t6;
t13 = l1.*t4;
t14 = l2.*t5;
t15 = m3.*t7;
t16 = m3.*t12.*1.0e+1;
t17 = -t15;
t18 = t11+t13;
t19 = t12+t13+t14;
A = reshape([-I1-d1.^2.*m1,0.0,0.0,t9-m2.*((t8+d2.*t3).^2+t18.^2),t9-d2.^2.*m2,0.0,t10-m3.*((t8+l2.*t3+d3.*cos(theta3)).^2+t19.^2),t10+t17-l2.^2.*m3-d3.*l2.*m3.*cos(theta2-theta3).*2.0,t10+t17],[3,3]);
if nargout > 1
    B = [m2.*t18.*1.0e+1+m3.*t19.*1.0e+1+d1.*m1.*t4.*1.0e+1;t16+m2.*t11.*1.0e+1+m3.*t14.*1.0e+1;t16];
end
end
