function [A,B] = Lagrange_matrices(in1,in2)
%Lagrange_matrices
%    [A,B] = Lagrange_matrices(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    16-May-2025 16:24:51

I = in2(2,:);
d1 = in2(3,:);
d2 = in2(4,:);
m = in2(1,:);
theta = in1(3,:);
theta1 = in2(5,:);
theta2 = in2(6,:);
thetadot = in1(6,:);
xdot = in1(4,:);
ydot = in1(5,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = theta+theta1;
t5 = theta+theta2;
t6 = xdot.^2;
t7 = ydot.^2;
t14 = m.*xdot.*ydot.*4.0;
t8 = d1.*t2;
t9 = d2.*t3;
t10 = cos(t4);
t11 = cos(t5);
t12 = sin(t4);
t13 = sin(t5);
t15 = t6+t7;
t16 = m.*t15.*2.0;
A = reshape([t16+m.*t6.*4.0,t14,0.0,-t12,-t13,t14,t16+m.*t7.*4.0,0.0,t10,t11,0.0,0.0,I,-t8,t9,t12,-t10,t8,0.0,0.0,t13,-t11,-t9,0.0,0.0],[5,5]);
if nargout > 1
    B = [0.0;0.0;0.0;t10.*thetadot.*xdot+t12.*thetadot.*ydot;t11.*thetadot.*xdot+t13.*thetadot.*ydot];
end
end
